name: alpha_skincare_app
description: AI-powered skin analysis & personalized recommendations.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  intl: ^0.19.0
  flutter_riverpod: ^2.5.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.2.1  # Downgraded to resolve conflict
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.2.9
  camera: ^0.11.0+1
  image: ^4.3.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  tflite_flutter: ^0.10.4
  flutter_local_notifications: ^17.2.3
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.2
  package_info_plus: ^8.0.0
  geolocator: ^12.0.0  # Use the latest version
  geocoding: ^3.0.0    # Use the latest version
  hive_flutter: ^1.1.0 # Add this line
  fl_chart: ^0.68.0 # Add this line (use the latest version)
  build_runner: ^2.4.9 # Add for code generation
  get_it: ^7.6.4
  dio: ^5.4.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  go_router: ^12.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter

dependency_overrides:
  web: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/tflite/skin_model.tflite
    - assets/images/
    - assets/animations/
    - assets/models/
    - assets/icons/