name: alpha_skincare_app
description: AI-powered skin analysis & personalized recommendations.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  lottie: ^3.1.2  # Use the latest version from pub.dev
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.4.0

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  firebase_messaging: ^15.2.9

  # Camera & image processing
  camera: ^0.11.2
  image: ^4.1.3
  image_picker: ^1.0.4
  permission_handler: ^12.0.1

  # On-device ML
  tflite_flutter: ^0.11.0

  # Local storage & notifications
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^19.3.0

  # UI & routing
  go_router: ^16.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/tflite/skin_model.tflite.tflite
