name: alpha_skincare_app
description: AI-powered skin analysis & personalized recommendations.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  intl: ^0.19.0
  flutter_riverpod: ^2.5.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.2.1  # Downgraded to resolve conflict
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.2.9
  camera: ^0.11.0+1
  image: ^4.3.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  tflite_flutter: ^0.10.4
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.3
  go_router: ^14.2.8
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.2
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter

dependency_overrides:
  web: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/tflite/skin_model.tflite